// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqLogin struct {
	RouteID              int32    `protobuf:"varint,1,opt,name=RouteID,proto3" json:"RouteID,omitempty"`
	ClientAddr           string   `protobuf:"bytes,2,opt,name=ClientAddr,proto3" json:"ClientAddr,omitempty"`
	SocketID             string   `protobuf:"bytes,3,opt,name=SocketID,proto3" json:"SocketID,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (m *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(m, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetRouteID() int32 {
	if m != nil {
		return m.RouteID
	}
	return 0
}

func (m *ReqLogin) GetClientAddr() string {
	if m != nil {
		return m.ClientAddr
	}
	return ""
}

func (m *ReqLogin) GetSocketID() string {
	if m != nil {
		return m.SocketID
	}
	return ""
}

func (m *ReqLogin) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type RespLogin struct {
	IsClose              bool     `protobuf:"varint,1,opt,name=IsClose,proto3" json:"IsClose,omitempty"`
	RouteID              int32    `protobuf:"varint,2,opt,name=RouteID,proto3" json:"RouteID,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespLogin) Reset()         { *m = RespLogin{} }
func (m *RespLogin) String() string { return proto.CompactTextString(m) }
func (*RespLogin) ProtoMessage()    {}
func (*RespLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *RespLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespLogin.Unmarshal(m, b)
}
func (m *RespLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespLogin.Marshal(b, m, deterministic)
}
func (m *RespLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespLogin.Merge(m, src)
}
func (m *RespLogin) XXX_Size() int {
	return xxx_messageInfo_RespLogin.Size(m)
}
func (m *RespLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RespLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RespLogin proto.InternalMessageInfo

func (m *RespLogin) GetIsClose() bool {
	if m != nil {
		return m.IsClose
	}
	return false
}

func (m *RespLogin) GetRouteID() int32 {
	if m != nil {
		return m.RouteID
	}
	return 0
}

func (m *RespLogin) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//微信登陆
type Login_C_Wechat struct {
	AgentID              int32    `protobuf:"varint,1,opt,name=AgentID,proto3" json:"AgentID,omitempty"`
	UserUin              string   `protobuf:"bytes,2,opt,name=UserUin,proto3" json:"UserUin,omitempty"`
	Gender               bool     `protobuf:"varint,3,opt,name=Gender,proto3" json:"Gender,omitempty"`
	NikeName             string   `protobuf:"bytes,4,opt,name=NikeName,proto3" json:"NikeName,omitempty"`
	HeadImageUrl         string   `protobuf:"bytes,5,opt,name=HeadImageUrl,proto3" json:"HeadImageUrl,omitempty"`
	MachineID            string   `protobuf:"bytes,6,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	DeviceType           int32    `protobuf:"varint,7,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_C_Wechat) Reset()         { *m = Login_C_Wechat{} }
func (m *Login_C_Wechat) String() string { return proto.CompactTextString(m) }
func (*Login_C_Wechat) ProtoMessage()    {}
func (*Login_C_Wechat) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *Login_C_Wechat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_C_Wechat.Unmarshal(m, b)
}
func (m *Login_C_Wechat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_C_Wechat.Marshal(b, m, deterministic)
}
func (m *Login_C_Wechat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_C_Wechat.Merge(m, src)
}
func (m *Login_C_Wechat) XXX_Size() int {
	return xxx_messageInfo_Login_C_Wechat.Size(m)
}
func (m *Login_C_Wechat) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_C_Wechat.DiscardUnknown(m)
}

var xxx_messageInfo_Login_C_Wechat proto.InternalMessageInfo

func (m *Login_C_Wechat) GetAgentID() int32 {
	if m != nil {
		return m.AgentID
	}
	return 0
}

func (m *Login_C_Wechat) GetUserUin() string {
	if m != nil {
		return m.UserUin
	}
	return ""
}

func (m *Login_C_Wechat) GetGender() bool {
	if m != nil {
		return m.Gender
	}
	return false
}

func (m *Login_C_Wechat) GetNikeName() string {
	if m != nil {
		return m.NikeName
	}
	return ""
}

func (m *Login_C_Wechat) GetHeadImageUrl() string {
	if m != nil {
		return m.HeadImageUrl
	}
	return ""
}

func (m *Login_C_Wechat) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *Login_C_Wechat) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

//手机号码登陆
type Login_C_Mobile struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	MachineID            string   `protobuf:"bytes,3,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	DeviceType           int32    `protobuf:"varint,4,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_C_Mobile) Reset()         { *m = Login_C_Mobile{} }
func (m *Login_C_Mobile) String() string { return proto.CompactTextString(m) }
func (*Login_C_Mobile) ProtoMessage()    {}
func (*Login_C_Mobile) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *Login_C_Mobile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_C_Mobile.Unmarshal(m, b)
}
func (m *Login_C_Mobile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_C_Mobile.Marshal(b, m, deterministic)
}
func (m *Login_C_Mobile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_C_Mobile.Merge(m, src)
}
func (m *Login_C_Mobile) XXX_Size() int {
	return xxx_messageInfo_Login_C_Mobile.Size(m)
}
func (m *Login_C_Mobile) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_C_Mobile.DiscardUnknown(m)
}

var xxx_messageInfo_Login_C_Mobile proto.InternalMessageInfo

func (m *Login_C_Mobile) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Login_C_Mobile) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Login_C_Mobile) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *Login_C_Mobile) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

//游客登陆
type Login_C_Visitor struct {
	MachineID            string   `protobuf:"bytes,1,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	DeviceType           int32    `protobuf:"varint,2,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_C_Visitor) Reset()         { *m = Login_C_Visitor{} }
func (m *Login_C_Visitor) String() string { return proto.CompactTextString(m) }
func (*Login_C_Visitor) ProtoMessage()    {}
func (*Login_C_Visitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}

func (m *Login_C_Visitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_C_Visitor.Unmarshal(m, b)
}
func (m *Login_C_Visitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_C_Visitor.Marshal(b, m, deterministic)
}
func (m *Login_C_Visitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_C_Visitor.Merge(m, src)
}
func (m *Login_C_Visitor) XXX_Size() int {
	return xxx_messageInfo_Login_C_Visitor.Size(m)
}
func (m *Login_C_Visitor) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_C_Visitor.DiscardUnknown(m)
}

var xxx_messageInfo_Login_C_Visitor proto.InternalMessageInfo

func (m *Login_C_Visitor) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *Login_C_Visitor) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

//登陆成功
type Login_S_Success struct {
	UserID               int32    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserGold             float32  `protobuf:"fixed32,2,opt,name=UserGold,proto3" json:"UserGold,omitempty"`
	UserDiamonds         float32  `protobuf:"fixed32,3,opt,name=UserDiamonds,proto3" json:"UserDiamonds,omitempty"`
	MemberOrder          int32    `protobuf:"varint,4,opt,name=MemberOrder,proto3" json:"MemberOrder,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	BinderCardNo         string   `protobuf:"bytes,6,opt,name=binderCardNo,proto3" json:"binderCardNo,omitempty"`
	FaceID               int32    `protobuf:"varint,7,opt,name=FaceID,proto3" json:"FaceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_S_Success) Reset()         { *m = Login_S_Success{} }
func (m *Login_S_Success) String() string { return proto.CompactTextString(m) }
func (*Login_S_Success) ProtoMessage()    {}
func (*Login_S_Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{5}
}

func (m *Login_S_Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_S_Success.Unmarshal(m, b)
}
func (m *Login_S_Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_S_Success.Marshal(b, m, deterministic)
}
func (m *Login_S_Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_S_Success.Merge(m, src)
}
func (m *Login_S_Success) XXX_Size() int {
	return xxx_messageInfo_Login_S_Success.Size(m)
}
func (m *Login_S_Success) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_S_Success.DiscardUnknown(m)
}

var xxx_messageInfo_Login_S_Success proto.InternalMessageInfo

func (m *Login_S_Success) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Login_S_Success) GetUserGold() float32 {
	if m != nil {
		return m.UserGold
	}
	return 0
}

func (m *Login_S_Success) GetUserDiamonds() float32 {
	if m != nil {
		return m.UserDiamonds
	}
	return 0
}

func (m *Login_S_Success) GetMemberOrder() int32 {
	if m != nil {
		return m.MemberOrder
	}
	return 0
}

func (m *Login_S_Success) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Login_S_Success) GetBinderCardNo() string {
	if m != nil {
		return m.BinderCardNo
	}
	return ""
}

func (m *Login_S_Success) GetFaceID() int32 {
	if m != nil {
		return m.FaceID
	}
	return 0
}

//登陆失败
type Login_S_Fail struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_S_Fail) Reset()         { *m = Login_S_Fail{} }
func (m *Login_S_Fail) String() string { return proto.CompactTextString(m) }
func (*Login_S_Fail) ProtoMessage()    {}
func (*Login_S_Fail) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{6}
}

func (m *Login_S_Fail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_S_Fail.Unmarshal(m, b)
}
func (m *Login_S_Fail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_S_Fail.Marshal(b, m, deterministic)
}
func (m *Login_S_Fail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_S_Fail.Merge(m, src)
}
func (m *Login_S_Fail) XXX_Size() int {
	return xxx_messageInfo_Login_S_Fail.Size(m)
}
func (m *Login_S_Fail) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_S_Fail.DiscardUnknown(m)
}

var xxx_messageInfo_Login_S_Fail proto.InternalMessageInfo

func (m *Login_S_Fail) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Login_S_Fail) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqLogin)(nil), "proto.ReqLogin")
	proto.RegisterType((*RespLogin)(nil), "proto.RespLogin")
	proto.RegisterType((*Login_C_Wechat)(nil), "proto.Login_C_Wechat")
	proto.RegisterType((*Login_C_Mobile)(nil), "proto.Login_C_Mobile")
	proto.RegisterType((*Login_C_Visitor)(nil), "proto.Login_C_Visitor")
	proto.RegisterType((*Login_S_Success)(nil), "proto.Login_S_Success")
	proto.RegisterType((*Login_S_Fail)(nil), "proto.Login_S_Fail")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcd, 0x8e, 0xda, 0x30,
	0x18, 0x6c, 0xf8, 0x8f, 0x17, 0x75, 0x57, 0x3e, 0x54, 0xd1, 0xaa, 0xaa, 0x50, 0x4e, 0x9c, 0x38,
	0xb4, 0x4f, 0xb0, 0x4d, 0xba, 0x80, 0x54, 0x58, 0xe4, 0x94, 0xf6, 0x88, 0x4c, 0xf2, 0x09, 0xac,
	0x0d, 0x31, 0xb5, 0x43, 0xab, 0xbe, 0x43, 0x9f, 0xb0, 0x6f, 0xd0, 0xb7, 0xa8, 0x3e, 0x63, 0x87,
	0xa4, 0x48, 0x7b, 0xc2, 0x33, 0x1f, 0x9a, 0xcc, 0x7c, 0x63, 0x93, 0x9b, 0x5c, 0xee, 0x44, 0x31,
	0x39, 0x2a, 0x59, 0x4a, 0xda, 0x35, 0x3f, 0x61, 0x49, 0x06, 0x0c, 0xbe, 0x7f, 0xc6, 0x01, 0x0d,
	0x48, 0x9f, 0xc9, 0x53, 0x09, 0xf3, 0x38, 0xf0, 0x46, 0xde, 0xb8, 0xcb, 0x1c, 0xa4, 0xef, 0x08,
	0x89, 0x72, 0x01, 0x45, 0xf9, 0x90, 0x65, 0x2a, 0x68, 0x8d, 0xbc, 0xb1, 0xcf, 0x6a, 0x0c, 0xbd,
	0x27, 0x83, 0x44, 0xa6, 0xcf, 0x50, 0xce, 0xe3, 0xa0, 0x6d, 0xa6, 0x15, 0xa6, 0x94, 0x74, 0x62,
	0x5e, 0xf2, 0xa0, 0x33, 0xf2, 0xc6, 0x43, 0x66, 0xce, 0x61, 0x42, 0x7c, 0x06, 0xfa, 0x58, 0x7d,
	0x76, 0xae, 0xa3, 0x5c, 0x6a, 0x30, 0x9f, 0x1d, 0x30, 0x07, 0xeb, 0x86, 0x5a, 0x4d, 0x43, 0x4e,
	0xb4, 0x5d, 0x13, 0xfd, 0xe3, 0x91, 0xd7, 0x46, 0x71, 0x13, 0x6d, 0xbe, 0x41, 0xba, 0xe7, 0x25,
	0x0a, 0x3c, 0xec, 0xa0, 0x28, 0x2f, 0x89, 0x2c, 0xc4, 0xc9, 0x5a, 0x83, 0x5a, 0x8b, 0xc2, 0xc6,
	0x71, 0x90, 0xbe, 0x21, 0xbd, 0x29, 0x14, 0x19, 0x28, 0x23, 0x3e, 0x60, 0x16, 0x61, 0xc6, 0xa5,
	0x78, 0x86, 0x25, 0x3f, 0x80, 0xc9, 0xe2, 0xb3, 0x0a, 0xd3, 0x90, 0x0c, 0x67, 0xc0, 0xb3, 0xf9,
	0x81, 0xef, 0x60, 0xad, 0xf2, 0xa0, 0x6b, 0xe6, 0x0d, 0x8e, 0xbe, 0x25, 0xfe, 0x82, 0xa7, 0x7b,
	0x51, 0x60, 0x9c, 0x9e, 0xf9, 0xc3, 0x85, 0xc0, 0x0d, 0xc7, 0xf0, 0x43, 0xa4, 0xf0, 0xe5, 0xd7,
	0x11, 0x82, 0xbe, 0x31, 0x5b, 0x63, 0xc2, 0xdf, 0xb5, 0x70, 0x0b, 0xb9, 0x15, 0x39, 0xd0, 0x11,
	0xb9, 0x59, 0xed, 0x65, 0x01, 0xcb, 0xd3, 0x61, 0x0b, 0xca, 0x04, 0xf4, 0x59, 0x9d, 0x42, 0xcb,
	0x2b, 0xae, 0xf5, 0x4f, 0xa9, 0x32, 0x9b, 0xb2, 0xc2, 0x4d, 0x3b, 0xed, 0x97, 0xed, 0x74, 0xae,
	0xec, 0x3c, 0x91, 0x5b, 0xe7, 0xe6, 0xab, 0xd0, 0xa2, 0x94, 0xaa, 0x29, 0xe8, 0xbd, 0x2c, 0xd8,
	0xba, 0x12, 0xfc, 0xeb, 0x39, 0xc5, 0x64, 0x93, 0x9c, 0xd2, 0x14, 0xb4, 0xc6, 0x26, 0xb0, 0x94,
	0xaa, 0x3c, 0x8b, 0x30, 0x16, 0x9e, 0xa6, 0x32, 0x3f, 0xc7, 0x6a, 0xb1, 0x0a, 0x63, 0x13, 0x78,
	0x8e, 0x05, 0x3f, 0xc8, 0x22, 0xd3, 0x26, 0x59, 0x8b, 0x35, 0x38, 0x5c, 0xdc, 0x02, 0x70, 0x41,
	0x4f, 0x0a, 0x6b, 0x3e, 0xa7, 0xab, 0x53, 0xff, 0xaf, 0xb6, 0x7b, 0xbd, 0xda, 0x90, 0x0c, 0xb7,
	0x02, 0xef, 0x45, 0xc4, 0x55, 0xb6, 0x94, 0xb6, 0xd0, 0x06, 0x87, 0xfe, 0x1f, 0x79, 0x8a, 0xeb,
	0x38, 0xf7, 0x69, 0x51, 0x38, 0x23, 0x43, 0x17, 0xf5, 0x91, 0x0b, 0x73, 0x33, 0x3e, 0x29, 0x25,
	0x55, 0x24, 0x33, 0xb0, 0x51, 0x2f, 0x04, 0xa6, 0x35, 0x60, 0xa1, 0x77, 0xae, 0x44, 0x87, 0xdf,
	0x7f, 0x24, 0x77, 0x46, 0x69, 0xca, 0x56, 0x51, 0x02, 0x0a, 0xb7, 0x49, 0x27, 0xa4, 0x3f, 0xe3,
	0x45, 0x96, 0x83, 0xa2, 0xb7, 0xe7, 0xb7, 0x3e, 0x71, 0x2f, 0xfc, 0xfe, 0xae, 0x22, 0xec, 0xe3,
	0x0b, 0x5f, 0x6d, 0x7b, 0x86, 0xfa, 0xf0, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x28, 0xc9, 0x5c,
	0x1e, 0x04, 0x00, 0x00,
}
