// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: login.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for LoginGRPCService service

type LoginGRPCService interface {
	//登陆服务处理接口
	Handler(ctx context.Context, in *ReqLogin, opts ...client.CallOption) (*RespLogin, error)
}

type loginGRPCService struct {
	c    client.Client
	name string
}

func NewLoginGRPCService(name string, c client.Client) LoginGRPCService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &loginGRPCService{
		c:    c,
		name: name,
	}
}

func (c *loginGRPCService) Handler(ctx context.Context, in *ReqLogin, opts ...client.CallOption) (*RespLogin, error) {
	req := c.c.NewRequest(c.name, "LoginGRPCService.Handler", in)
	out := new(RespLogin)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LoginGRPCService service

type LoginGRPCServiceHandler interface {
	//登陆服务处理接口
	Handler(context.Context, *ReqLogin, *RespLogin) error
}

func RegisterLoginGRPCServiceHandler(s server.Server, hdlr LoginGRPCServiceHandler, opts ...server.HandlerOption) error {
	type loginGRPCService interface {
		Handler(ctx context.Context, in *ReqLogin, out *RespLogin) error
	}
	type LoginGRPCService struct {
		loginGRPCService
	}
	h := &loginGRPCServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&LoginGRPCService{h}, opts...))
}

type loginGRPCServiceHandler struct {
	LoginGRPCServiceHandler
}

func (h *loginGRPCServiceHandler) Handler(ctx context.Context, in *ReqLogin, out *RespLogin) error {
	return h.LoginGRPCServiceHandler.Handler(ctx, in, out)
}
