// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DbReqHost struct {
	HostName             string   `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DbReqHost) Reset()         { *m = DbReqHost{} }
func (m *DbReqHost) String() string { return proto.CompactTextString(m) }
func (*DbReqHost) ProtoMessage()    {}
func (*DbReqHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{0}
}

func (m *DbReqHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DbReqHost.Unmarshal(m, b)
}
func (m *DbReqHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DbReqHost.Marshal(b, m, deterministic)
}
func (m *DbReqHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DbReqHost.Merge(m, src)
}
func (m *DbReqHost) XXX_Size() int {
	return xxx_messageInfo_DbReqHost.Size(m)
}
func (m *DbReqHost) XXX_DiscardUnknown() {
	xxx_messageInfo_DbReqHost.DiscardUnknown(m)
}

var xxx_messageInfo_DbReqHost proto.InternalMessageInfo

func (m *DbReqHost) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

type DbHost struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HostName             string   `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DbHost) Reset()         { *m = DbHost{} }
func (m *DbHost) String() string { return proto.CompactTextString(m) }
func (*DbHost) ProtoMessage()    {}
func (*DbHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{1}
}

func (m *DbHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DbHost.Unmarshal(m, b)
}
func (m *DbHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DbHost.Marshal(b, m, deterministic)
}
func (m *DbHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DbHost.Merge(m, src)
}
func (m *DbHost) XXX_Size() int {
	return xxx_messageInfo_DbHost.Size(m)
}
func (m *DbHost) XXX_DiscardUnknown() {
	xxx_messageInfo_DbHost.DiscardUnknown(m)
}

var xxx_messageInfo_DbHost proto.InternalMessageInfo

func (m *DbHost) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DbHost) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *DbHost) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *DbHost) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type DbRespHost struct {
	Code                 int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Host                 []*DbHost `protobuf:"bytes,3,rep,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DbRespHost) Reset()         { *m = DbRespHost{} }
func (m *DbRespHost) String() string { return proto.CompactTextString(m) }
func (*DbRespHost) ProtoMessage()    {}
func (*DbRespHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{2}
}

func (m *DbRespHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DbRespHost.Unmarshal(m, b)
}
func (m *DbRespHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DbRespHost.Marshal(b, m, deterministic)
}
func (m *DbRespHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DbRespHost.Merge(m, src)
}
func (m *DbRespHost) XXX_Size() int {
	return xxx_messageInfo_DbRespHost.Size(m)
}
func (m *DbRespHost) XXX_DiscardUnknown() {
	xxx_messageInfo_DbRespHost.DiscardUnknown(m)
}

var xxx_messageInfo_DbRespHost proto.InternalMessageInfo

func (m *DbRespHost) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DbRespHost) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DbRespHost) GetHost() []*DbHost {
	if m != nil {
		return m.Host
	}
	return nil
}

func init() {
	proto.RegisterType((*DbReqHost)(nil), "proto.DbReqHost")
	proto.RegisterType((*DbHost)(nil), "proto.DbHost")
	proto.RegisterType((*DbRespHost)(nil), "proto.DbRespHost")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor_8817812184a13374) }

var fileDescriptor_8817812184a13374 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x4f, 0xbd, 0x4e, 0xc6, 0x30,
	0x0c, 0xe4, 0x4b, 0xd3, 0x3f, 0x23, 0x10, 0x78, 0x8a, 0x3a, 0x95, 0x2c, 0x74, 0xaa, 0x50, 0x91,
	0x78, 0x82, 0x4a, 0x30, 0x31, 0x64, 0x62, 0x61, 0x68, 0x48, 0x04, 0x1d, 0xaa, 0x84, 0x26, 0xef,
	0x2f, 0x54, 0xf7, 0x47, 0x74, 0xb2, 0x7d, 0x3e, 0xfb, 0xee, 0xa0, 0x30, 0xba, 0xf5, 0xb3, 0x8b,
	0x0e, 0x53, 0x2a, 0xf2, 0x11, 0xca, 0x5e, 0x2b, 0xfb, 0xfb, 0xe6, 0x42, 0xc4, 0x0a, 0x8a, 0x1f,
	0x17, 0xe2, 0xfb, 0x30, 0x59, 0x71, 0xa9, 0x2f, 0x4d, 0xa9, 0x8e, 0x59, 0x7e, 0x40, 0xd6, 0x6b,
	0x62, 0xdd, 0x02, 0x1b, 0x0d, 0xed, 0x53, 0xc5, 0x46, 0x73, 0xba, 0x62, 0xe7, 0x2b, 0xe2, 0x7a,
	0x91, 0x10, 0xca, 0x46, 0x8f, 0x08, 0xdc, 0xbb, 0x39, 0x0a, 0x4e, 0x08, 0xf5, 0xf2, 0x13, 0x60,
	0xb1, 0x10, 0x3c, 0x7d, 0x47, 0xe0, 0x5f, 0xce, 0xd8, 0xed, 0x3f, 0xf5, 0x28, 0x20, 0x9f, 0x6c,
	0x08, 0xc3, 0xf7, 0x2e, 0xb0, 0x8f, 0xf8, 0x00, 0x7c, 0xd1, 0x12, 0x49, 0x9d, 0x34, 0xd7, 0xdd,
	0xcd, 0x9a, 0xad, 0x5d, 0x8d, 0x2a, 0x5a, 0x75, 0x2f, 0xc0, 0x7a, 0x8d, 0x4f, 0x90, 0xbf, 0xda,
	0x48, 0x0a, 0x77, 0x07, 0x6b, 0xcb, 0x5d, 0xdd, 0xff, 0x43, 0x56, 0x1b, 0xf2, 0x4a, 0x67, 0x84,
	0x3d, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x24, 0x58, 0xc9, 0xfb, 0x33, 0x01, 0x00, 0x00,
}
