// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//微信登陆
type LoginDB_C_Wechat struct {
	AgentID              int32    `protobuf:"varint,1,opt,name=AgentID,proto3" json:"AgentID,omitempty"`
	UserUin              string   `protobuf:"bytes,2,opt,name=UserUin,proto3" json:"UserUin,omitempty"`
	Gender               bool     `protobuf:"varint,3,opt,name=Gender,proto3" json:"Gender,omitempty"`
	NikeName             string   `protobuf:"bytes,4,opt,name=NikeName,proto3" json:"NikeName,omitempty"`
	HeadImageUrl         string   `protobuf:"bytes,5,opt,name=HeadImageUrl,proto3" json:"HeadImageUrl,omitempty"`
	MachineID            string   `protobuf:"bytes,6,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	DeviceType           int32    `protobuf:"varint,7,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	ClientAddr           string   `protobuf:"bytes,8,opt,name=ClientAddr,proto3" json:"ClientAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginDB_C_Wechat) Reset()         { *m = LoginDB_C_Wechat{} }
func (m *LoginDB_C_Wechat) String() string { return proto.CompactTextString(m) }
func (*LoginDB_C_Wechat) ProtoMessage()    {}
func (*LoginDB_C_Wechat) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *LoginDB_C_Wechat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginDB_C_Wechat.Unmarshal(m, b)
}
func (m *LoginDB_C_Wechat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginDB_C_Wechat.Marshal(b, m, deterministic)
}
func (m *LoginDB_C_Wechat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginDB_C_Wechat.Merge(m, src)
}
func (m *LoginDB_C_Wechat) XXX_Size() int {
	return xxx_messageInfo_LoginDB_C_Wechat.Size(m)
}
func (m *LoginDB_C_Wechat) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginDB_C_Wechat.DiscardUnknown(m)
}

var xxx_messageInfo_LoginDB_C_Wechat proto.InternalMessageInfo

func (m *LoginDB_C_Wechat) GetAgentID() int32 {
	if m != nil {
		return m.AgentID
	}
	return 0
}

func (m *LoginDB_C_Wechat) GetUserUin() string {
	if m != nil {
		return m.UserUin
	}
	return ""
}

func (m *LoginDB_C_Wechat) GetGender() bool {
	if m != nil {
		return m.Gender
	}
	return false
}

func (m *LoginDB_C_Wechat) GetNikeName() string {
	if m != nil {
		return m.NikeName
	}
	return ""
}

func (m *LoginDB_C_Wechat) GetHeadImageUrl() string {
	if m != nil {
		return m.HeadImageUrl
	}
	return ""
}

func (m *LoginDB_C_Wechat) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *LoginDB_C_Wechat) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *LoginDB_C_Wechat) GetClientAddr() string {
	if m != nil {
		return m.ClientAddr
	}
	return ""
}

//手机号码登陆
type LoginDB_C_Mobile struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	MachineID            string   `protobuf:"bytes,3,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	DeviceType           int32    `protobuf:"varint,4,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	ClientAddr           string   `protobuf:"bytes,5,opt,name=ClientAddr,proto3" json:"ClientAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginDB_C_Mobile) Reset()         { *m = LoginDB_C_Mobile{} }
func (m *LoginDB_C_Mobile) String() string { return proto.CompactTextString(m) }
func (*LoginDB_C_Mobile) ProtoMessage()    {}
func (*LoginDB_C_Mobile) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *LoginDB_C_Mobile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginDB_C_Mobile.Unmarshal(m, b)
}
func (m *LoginDB_C_Mobile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginDB_C_Mobile.Marshal(b, m, deterministic)
}
func (m *LoginDB_C_Mobile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginDB_C_Mobile.Merge(m, src)
}
func (m *LoginDB_C_Mobile) XXX_Size() int {
	return xxx_messageInfo_LoginDB_C_Mobile.Size(m)
}
func (m *LoginDB_C_Mobile) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginDB_C_Mobile.DiscardUnknown(m)
}

var xxx_messageInfo_LoginDB_C_Mobile proto.InternalMessageInfo

func (m *LoginDB_C_Mobile) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *LoginDB_C_Mobile) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginDB_C_Mobile) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *LoginDB_C_Mobile) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *LoginDB_C_Mobile) GetClientAddr() string {
	if m != nil {
		return m.ClientAddr
	}
	return ""
}

//游客登陆
type LoginDB_C_Visitor struct {
	MachineID            string   `protobuf:"bytes,1,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	DeviceType           int32    `protobuf:"varint,2,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	ClientAddr           string   `protobuf:"bytes,3,opt,name=ClientAddr,proto3" json:"ClientAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginDB_C_Visitor) Reset()         { *m = LoginDB_C_Visitor{} }
func (m *LoginDB_C_Visitor) String() string { return proto.CompactTextString(m) }
func (*LoginDB_C_Visitor) ProtoMessage()    {}
func (*LoginDB_C_Visitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *LoginDB_C_Visitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginDB_C_Visitor.Unmarshal(m, b)
}
func (m *LoginDB_C_Visitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginDB_C_Visitor.Marshal(b, m, deterministic)
}
func (m *LoginDB_C_Visitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginDB_C_Visitor.Merge(m, src)
}
func (m *LoginDB_C_Visitor) XXX_Size() int {
	return xxx_messageInfo_LoginDB_C_Visitor.Size(m)
}
func (m *LoginDB_C_Visitor) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginDB_C_Visitor.DiscardUnknown(m)
}

var xxx_messageInfo_LoginDB_C_Visitor proto.InternalMessageInfo

func (m *LoginDB_C_Visitor) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *LoginDB_C_Visitor) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *LoginDB_C_Visitor) GetClientAddr() string {
	if m != nil {
		return m.ClientAddr
	}
	return ""
}

//登陆反馈
type LoginDB_S_Resp struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginDB_S_Resp) Reset()         { *m = LoginDB_S_Resp{} }
func (m *LoginDB_S_Resp) String() string { return proto.CompactTextString(m) }
func (*LoginDB_S_Resp) ProtoMessage()    {}
func (*LoginDB_S_Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *LoginDB_S_Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginDB_S_Resp.Unmarshal(m, b)
}
func (m *LoginDB_S_Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginDB_S_Resp.Marshal(b, m, deterministic)
}
func (m *LoginDB_S_Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginDB_S_Resp.Merge(m, src)
}
func (m *LoginDB_S_Resp) XXX_Size() int {
	return xxx_messageInfo_LoginDB_S_Resp.Size(m)
}
func (m *LoginDB_S_Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginDB_S_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginDB_S_Resp proto.InternalMessageInfo

func (m *LoginDB_S_Resp) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *LoginDB_S_Resp) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *LoginDB_S_Resp) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginDB_C_Wechat)(nil), "proto.LoginDB_C_Wechat")
	proto.RegisterType((*LoginDB_C_Mobile)(nil), "proto.LoginDB_C_Mobile")
	proto.RegisterType((*LoginDB_C_Visitor)(nil), "proto.LoginDB_C_Visitor")
	proto.RegisterType((*LoginDB_S_Resp)(nil), "proto.LoginDB_S_Resp")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x6e, 0xda, 0x40,
	0x18, 0xac, 0x01, 0xf3, 0xf3, 0x81, 0xaa, 0x76, 0xa5, 0xb6, 0x2b, 0x54, 0x55, 0x96, 0x4f, 0x9c,
	0x38, 0xb4, 0x0f, 0x50, 0x11, 0x3b, 0x22, 0x48, 0x01, 0x21, 0x13, 0x92, 0x5b, 0xd0, 0x82, 0x3f,
	0x99, 0x55, 0x8c, 0x97, 0xac, 0x9d, 0x44, 0x79, 0xa9, 0xbc, 0x4f, 0xde, 0x25, 0x87, 0x68, 0xd7,
	0x36, 0x60, 0x10, 0x70, 0xb2, 0x67, 0xc6, 0x3b, 0x33, 0xfb, 0xf9, 0x83, 0x66, 0x28, 0x02, 0x1e,
	0x75, 0xd7, 0x52, 0x24, 0x82, 0x98, 0xfa, 0x61, 0x7f, 0x18, 0xf0, 0xed, 0x5a, 0xd1, 0xee, 0xc5,
	0xcc, 0x99, 0xdd, 0xe1, 0x62, 0xc9, 0x12, 0x42, 0xa1, 0xd6, 0x0b, 0x30, 0x4a, 0x06, 0x2e, 0x35,
	0x2c, 0xa3, 0x63, 0x7a, 0x39, 0x54, 0xca, 0x34, 0x46, 0x39, 0xe5, 0x11, 0x2d, 0x59, 0x46, 0xa7,
	0xe1, 0xe5, 0x90, 0xfc, 0x84, 0x6a, 0x1f, 0x23, 0x1f, 0x25, 0x2d, 0x5b, 0x46, 0xa7, 0xee, 0x65,
	0x88, 0xb4, 0xa1, 0x3e, 0xe2, 0x0f, 0x38, 0x62, 0x2b, 0xa4, 0x15, 0x7d, 0x64, 0x83, 0x89, 0x0d,
	0xad, 0x2b, 0x64, 0xfe, 0x60, 0xc5, 0x02, 0x9c, 0xca, 0x90, 0x9a, 0x5a, 0x2f, 0x70, 0xe4, 0x37,
	0x34, 0x86, 0x6c, 0xb1, 0xe4, 0x11, 0x0e, 0x5c, 0x5a, 0xd5, 0x1f, 0x6c, 0x09, 0xf2, 0x07, 0xc0,
	0xc5, 0x67, 0xbe, 0xc0, 0x9b, 0xd7, 0x35, 0xd2, 0x9a, 0x2e, 0xbb, 0xc3, 0x28, 0xdd, 0x09, 0x39,
	0x46, 0x49, 0xcf, 0xf7, 0x25, 0xad, 0xeb, 0xe3, 0x3b, 0x8c, 0xfd, 0x56, 0xb8, 0xfe, 0x50, 0xcc,
	0x79, 0x88, 0xc4, 0x82, 0xe6, 0x78, 0x29, 0x22, 0x1c, 0x3d, 0xad, 0xe6, 0x28, 0xf5, 0x08, 0x1a,
	0xde, 0x2e, 0xa5, 0x2e, 0x35, 0x66, 0x71, 0xfc, 0x22, 0xa4, 0x9f, 0xcd, 0x61, 0x83, 0x8b, 0x85,
	0xcb, 0xa7, 0x0b, 0x57, 0xce, 0x14, 0x36, 0x0f, 0x0a, 0x3f, 0xc2, 0xf7, 0x6d, 0xdf, 0x5b, 0x1e,
	0xf3, 0x44, 0xc8, 0x62, 0xa4, 0x71, 0x3a, 0xb2, 0x74, 0x26, 0xb2, 0x7c, 0x10, 0x79, 0x0f, 0x5f,
	0xf3, 0xc8, 0xc9, 0xcc, 0xc3, 0x78, 0xad, 0xf2, 0x2e, 0xa5, 0x14, 0xd2, 0x11, 0x3e, 0x66, 0x1b,
	0xb2, 0x25, 0xd4, 0x70, 0x34, 0x18, 0xc6, 0x41, 0x3e, 0x9c, 0x1c, 0x13, 0x02, 0x15, 0x97, 0x25,
	0x4c, 0xa7, 0xb4, 0x3c, 0xfd, 0xfe, 0xf7, 0xdd, 0x00, 0x92, 0x05, 0xf4, 0xbd, 0xb1, 0x33, 0x41,
	0xa9, 0xaa, 0x91, 0xff, 0xd0, 0x4c, 0xd7, 0x51, 0x6b, 0xe4, 0x57, 0xba, 0xb7, 0xdd, 0xfd, 0x65,
	0x6d, 0xff, 0xd8, 0x13, 0xd2, 0x8e, 0xf6, 0x17, 0x65, 0x90, 0xfe, 0xd0, 0x63, 0x06, 0xa9, 0x7a,
	0xdc, 0xa0, 0x07, 0xad, 0x6c, 0xc2, 0xa9, 0x03, 0x3d, 0x70, 0xc8, 0xe4, 0xa3, 0x16, 0xf3, 0xaa,
	0xe6, 0xff, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff, 0x40, 0x31, 0x1d, 0x9f, 0x7b, 0x03, 0x00, 0x00,
}
