# 服务端监听配置
service:
  mode: debug|release|test
  port: :13000
  tcp_port: :13001
  app_read_timeout: 120
  app_write_timeout: 120
  max_page_size: 100

# log配置
log:
  path: /../config/log.xml


# 数据库配置
db:
  dialect: mysql
  host: localhost:3306
  user: root
  pass: 123456
  db: wallet
  max_open_connections: 20
  max_idle_connections: 10
  enable_log: false

# 数据库配置
db_treasure:
  dialect: mysql
  host: 47.56.172.167:3306
  user: root
  pass: Ystw892n7Ta2$
  db: xjtreasuredb
  max_open_connections: 20
  max_idle_connections: 10
  enable_log: true

# 数据库配置
db_platform:
  dialect: mysql
  host: 47.56.172.167:3306
  user: root
  pass: Ystw892n7Ta2$
  db: xjplatformdb
  max_open_connections: 20
  max_idle_connections: 10
  enable_log: true

# 数据库配置
db_record:
  dialect: mysql
  host: 127.0.0.1:3306
  user: root
  pass: 123456
  db: xjrecorddb
  max_open_connections: 20
  max_idle_connections: 10
  enable_log: true

# redis
redis:
  host: 127.0.0.1:6379
  pass: uJREJW9DNIk2H3I96ayz
  db: 4

# wss
wss:
  heart_beat_time: 5
