// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqSignUp struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSignUp) Reset()         { *m = ReqSignUp{} }
func (m *ReqSignUp) String() string { return proto.CompactTextString(m) }
func (*ReqSignUp) ProtoMessage()    {}
func (*ReqSignUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *ReqSignUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSignUp.Unmarshal(m, b)
}
func (m *ReqSignUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSignUp.Marshal(b, m, deterministic)
}
func (m *ReqSignUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSignUp.Merge(m, src)
}
func (m *ReqSignUp) XXX_Size() int {
	return xxx_messageInfo_ReqSignUp.Size(m)
}
func (m *ReqSignUp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSignUp.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSignUp proto.InternalMessageInfo

func (m *ReqSignUp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqSignUp) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RespSignUp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSignUp) Reset()         { *m = RespSignUp{} }
func (m *RespSignUp) String() string { return proto.CompactTextString(m) }
func (*RespSignUp) ProtoMessage()    {}
func (*RespSignUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *RespSignUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSignUp.Unmarshal(m, b)
}
func (m *RespSignUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSignUp.Marshal(b, m, deterministic)
}
func (m *RespSignUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSignUp.Merge(m, src)
}
func (m *RespSignUp) XXX_Size() int {
	return xxx_messageInfo_RespSignUp.Size(m)
}
func (m *RespSignUp) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSignUp.DiscardUnknown(m)
}

var xxx_messageInfo_RespSignUp proto.InternalMessageInfo

func (m *RespSignUp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespSignUp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqSignUp)(nil), "proto.ReqSignUp")
	proto.RegisterType((*RespSignUp)(nil), "proto.RespSignUp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xce, 0x5c, 0x9c, 0x41, 0xa9,
	0x85, 0xc1, 0x99, 0xe9, 0x79, 0xa1, 0x05, 0x42, 0x52, 0x5c, 0x1c, 0x20, 0x15, 0x79, 0x89, 0xb9,
	0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0x3e, 0x48, 0xae, 0x20, 0xb1, 0xb8, 0xb8,
	0x3c, 0xbf, 0x28, 0x45, 0x82, 0x09, 0x22, 0x07, 0xe3, 0x2b, 0x59, 0x71, 0x71, 0x05, 0xa5, 0x16,
	0x17, 0x40, 0x4d, 0x11, 0xe2, 0x62, 0x49, 0xce, 0x4f, 0x81, 0x98, 0xc0, 0x1a, 0x04, 0x66, 0x0b,
	0x49, 0x70, 0xb1, 0xe7, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x42, 0x35, 0xc3, 0xb8, 0x46, 0xe6,
	0x5c, 0x2c, 0xa1, 0xc5, 0xa9, 0x45, 0x42, 0xfa, 0x5c, 0x6c, 0x50, 0xfd, 0x02, 0x10, 0x17, 0xea,
	0xc1, 0xdd, 0x25, 0x25, 0x08, 0x17, 0x81, 0x59, 0xa2, 0xc4, 0x90, 0xc4, 0x06, 0x16, 0x33, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x70, 0x78, 0x08, 0xa7, 0xd5, 0x00, 0x00, 0x00,
}
